# dependabot
# Ref: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# ------------------------------------------------------------------------------
version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  commit-message:
    prefix: ci
  labels:
  - 'type: ci'
  - 'deps: github-actions'
  groups:
    github-actions:
      patterns:
      - '*'
- package-ecosystem: pip
  directory: /
  schedule:
    interval: monthly
  commit-message:
    prefix: build
    include: scope
  labels:
  - 'type: build'
  - 'deps: python'
  groups:
    docs:
      patterns:
      - mkdocs*
    test:
      patterns:
      - pytest*
- package-ecosystem: pip
  directory: /.github/workflows
  schedule:
    interval: monthly
  commit-message:
    prefix: ci
  labels:
  - 'type: ci'
  - 'deps: python'
  groups:
    constraints:
      patterns:
      - '*'
