# Do not edit this file directly. It has been autogenerated from
# tests/integration/test_async_client.py
# SPDX-FileCopyrightText: 2024 Heinz-Alexander Fütterer
#
# SPDX-License-Identifier: MIT

from __future__ import annotations

from typing import TYPE_CHECKING

import httpx
import pytest
from pandas import DataFrame

from re3data import RepositoryNotFoundError, Response, ReturnType
from re3data._resources import Repository, RepositoryName, RepositorySummary

if TYPE_CHECKING:
    from respx import Route

    from re3data import Client


def test_client_list_repositories_default_return_type(client: Client, mock_repository_list_route: Route) -> None:
    response = client.repositories.list()
    assert isinstance(response, list)
    # there are 3 canned repositories in the mocked response
    assert len(response) == 3
    assert isinstance(response[0], RepositorySummary)


def test_client_list_repositories_dataclass(client: Client, mock_repository_list_route: Route) -> None:
    response = client.repositories.list(return_type=ReturnType.DATACLASS)
    assert isinstance(response, list)
    # there are 3 canned repositories in the mocked response
    assert len(response) == 3
    assert isinstance(response[0], RepositorySummary)


def test_client_list_repositories_invalid_return_type(client: Client) -> None:
    with pytest.raises(ValueError, match="Invalid value for `return_type`"):
        client.repositories.list(return_type="json")  # type: ignore[arg-type]


def test_client_list_repositories_xml(client: Client, mock_repository_list_route: Route) -> None:
    response = client.repositories.list(return_type=ReturnType.XML)
    assert isinstance(response, str)
    assert '<?xml version="1.0" encoding="UTF-8"?>' in response
    assert "<list>" in response
    assert "<repository>" in response


def test_client_list_repositories_json(client: Client, mock_repository_list_route: Route) -> None:
    response = client.repositories.list(return_type=ReturnType.JSON)
    assert isinstance(response, str)
    assert '"id": "r3d100010371",' in response
    assert '"doi": "https://doi.org/10.17616/R3P594",' in response


def test_client_list_repositories_dict(client: Client, mock_repository_list_route: Route) -> None:
    response = client.repositories.list(return_type=ReturnType.DICT)
    assert isinstance(response, list)
    repository = response[0]
    assert isinstance(repository, dict)
    assert repository["id"] == "r3d100010371"


def test_client_list_repositories_csv(client: Client, mock_repository_list_route: Route) -> None:
    response = client.repositories.list(return_type=ReturnType.CSV)
    assert isinstance(response, str)
    assert response.startswith("id,doi,name,")
    assert "r3d100010371" in response
    assert "https://doi.org/10.17616/R3P594" in response


def test_client_list_repositories_dataframe(client: Client, mock_repository_list_route: Route) -> None:
    response = client.repositories.list(return_type=ReturnType.DATAFRAME)
    assert isinstance(response, DataFrame)
    assert response.shape == (3, 5)
    assert response["id"].loc[0] == "r3d100010371"


def test_client_list_repositories_response(client: Client, mock_repository_list_route: Route) -> None:
    response = client.repositories.list(return_type=ReturnType.RESPONSE)
    assert isinstance(response, Response)
    assert response.status_code == httpx.codes.OK


def test_client_list_repositories_query_string(client: Client, mock_repository_list_query_route: Route) -> None:
    response = client.repositories.list(query="biosharing")
    assert isinstance(response, list)
    repository = response[0]
    assert isinstance(repository, RepositorySummary)
    assert repository.id == "r3d100010142"


def test_client_list_repositories_query_string_returns_empty_list(
    client: Client, mock_repository_list_query_empty_list_route: Route
) -> None:
    response = client.repositories.list(query="XXX")
    assert isinstance(response, list)
    assert response == []


def test_client_list_repositories_count(client: Client, mock_repository_list_route: Route) -> None:
    response = client.repositories.list(count=True)
    assert isinstance(response, int)
    assert response == 3


def test_client_list_repositories_count_empty_list(
    client: Client, mock_repository_list_query_empty_list_route: Route
) -> None:
    response = client.repositories.list(query="XXX", count=True)
    assert isinstance(response, int)
    assert response == 0


def test_client_get_single_repository_default_return_type(
    client: Client, mock_repository_get_route: Route, zenodo_id: str
) -> None:
    response = client.repositories.get(zenodo_id)
    assert isinstance(response, Repository)
    assert response.id == zenodo_id
    assert isinstance(response.repository_name, RepositoryName)
    assert response.repository_name.value == "Zenodo"


def test_client_get_single_repository_xml(client: Client, mock_repository_get_route: Route, zenodo_id: str) -> None:
    response = client.repositories.get(zenodo_id, return_type=ReturnType.XML)
    assert isinstance(response, str)
    assert '<?xml version="1.0" encoding="utf-8"?>' in response
    assert "<r3d:repository>" in response
    assert "<r3d:re3data.orgIdentifier>r3d100010468</r3d:re3data.orgIdentifier>" in response


def test_client_get_single_repository_json(client: Client, mock_repository_get_route: Route, zenodo_id: str) -> None:
    response = client.repositories.get(zenodo_id, return_type=ReturnType.JSON)
    assert isinstance(response, str)
    assert "{" in response
    assert '"re3data.orgIdentifier": "r3d100010468",' in response


def test_client_get_single_repository_dict(client: Client, mock_repository_get_route: Route, zenodo_id: str) -> None:
    response = client.repositories.get(zenodo_id, return_type=ReturnType.DICT)
    assert isinstance(response, dict)
    assert response["re3data.orgIdentifier"] == zenodo_id


def test_client_get_single_repository_csv(client: Client, mock_repository_get_route: Route, zenodo_id: str) -> None:
    response = client.repositories.get(zenodo_id, return_type=ReturnType.CSV)
    assert isinstance(response, str)
    assert response.startswith("re3data.orgIdentifier,additionalName,repositoryURL,")
    assert "r3d100010468" in response


def test_client_get_single_repository_dataframe(
    client: Client, mock_repository_get_route: Route, zenodo_id: str
) -> None:
    response = client.repositories.get(zenodo_id, return_type=ReturnType.DATAFRAME)
    assert isinstance(response, DataFrame)
    assert response.shape == (1, 43)
    assert response["re3data.orgIdentifier"].loc[0] == "r3d100010468"


def test_client_get_single_repository_response(
    client: Client, mock_repository_get_route: Route, zenodo_id: str
) -> None:
    response = client.repositories.get(zenodo_id, return_type=ReturnType.RESPONSE)
    assert isinstance(response, Response)
    assert response.status_code == httpx.codes.OK


@pytest.mark.default_cassette("repository.yaml")
@pytest.mark.vcr
def test_client_get_invalid_repository_id(client: Client) -> None:
    with pytest.raises(RepositoryNotFoundError):
        client.repositories.get("XXX")


def test_client_handles_server_error(client: Client, mock_server_error: Route) -> None:
    with pytest.raises(httpx.HTTPStatusError):
        client.repositories.list()
