# mkdocs
# Ref: https://www.mkdocs.org/user-guide/configuration/
# ------------------------------------------------------------------------------

site_name: python-re3data
site_description: The pythonic client for the re3data API.
repo_name: afuetterer/python-re3data
repo_url: https://github.com/afuetterer/python-re3data
watch:
- ../README.md
- ../src
docs_dir: .
site_dir: ../site
edit_uri: edit/main/docs/

nav:
- Home: index.md
- Meta:
  - Contributor Guide: contributing.md
  - License: license.md

theme:
  name: material
  features:
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - navigation.footer
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

plugins:
- search
- include-markdown
- mkdocstrings:
    default_handler: python

markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
