name: Handle stale issues and PRs

on:
  schedule:
    # run once a month at midnight of the first day of the month
  - cron: 0 0 1 * *
  workflow_dispatch: # run manually from actions tab

# Set permissions at the job level.
permissions: {}

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: afuetterer/.github/.github/workflows/_stale.yml@main
